# Generated by Django 6.1 on 2026-08-19 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Activo')),
                ('tipo', models.CharField(choices=[('Servidor', 'Servidor / Máquina Virtual'), ('Base_de_Datos', 'Base de Datos'), ('Red', 'Dispositivo de Red (Router/Switch/Firewall)'), ('Equipo_Usuario', 'Equipo de Usuario / Laptop'), ('Aplicacion', 'Aplicación Web / API')], default='Servidor', max_length=30)),
                ('criticidad', models.CharField(choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja')], default='Media', max_length=10)),
                ('ubicacion_ip', models.CharField(max_length=100, verbose_name='Dirección IP / Ubicación')),
                ('descripcion', models.TextField(verbose_name='Descripción detallada')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Incidente')),
                ('descripcion', models.TextField(verbose_name='Descripción del Suceso')),
                ('severidad', models.CharField(choices=[('Critico', 'Crítico'), ('Alto', 'Alto'), ('Medio', 'Medio'), ('Bajo', 'Bajo')], default='Medio', max_length=10)),
                ('estado', models.CharField(choices=[('Abierto', 'Abierto'), ('En_Investigacion', 'En Investigación'), ('Resuelto', 'Resuelto'), ('Cerrado', 'Cerrado')], default='Abierto', max_length=20)),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo_afectado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidentes', to='gestion.activo', verbose_name='Activo Afectado')),
                ('reportado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidentes_reportados', to=settings.AUTH_USER_MODEL, verbose_name='Reportado Por')),
            ],
            options={
                'ordering': ['-fecha_reporte'],
            },
        ),
    ]
