# Generated by Django 6.1 on 2026-08-31 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_historialincidente'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='en_servicio',
            field=models.BooleanField(default=True, verbose_name='¿En servicio?'),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='activo_afectado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidentes', to='gestion.activo', verbose_name='Activo Afectado'),
        ),
    ]
