# Generated by Django 6.1 on 2026-08-31 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_activo_en_servicio_alter_incidente_activo_afectado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activo',
            name='en_servicio',
        ),
        migrations.AlterField(
            model_name='incidente',
            name='activo_afectado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidentes', to='gestion.activo', verbose_name='Activo Afectado'),
        ),
    ]
