# Generated by Django 6.1 on 2026-08-19 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Analista', 'Analista de Seguridad'), ('Administrador', 'Administrador de IT'), ('Auditor', 'Auditor Interno')], default='Analista', max_length=20)),
                ('departamento', models.CharField(blank=True, max_length=100, verbose_name='Departamento o Área')),
                ('bio', models.TextField(blank=True, verbose_name='Biografía o Notas')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatares/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
