# Generated by Django 6.1 on 2026-08-29 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='role',
        ),
    ]
