# Generated by Django 6.1 on 2026-08-31 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_perfil_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='departamento',
        ),
    ]
